/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsVali;

import java.util.ArrayList;
import pachet.clase.valentin.MasinaSpalatRufe;
import pachet.clasegeneratoare.vali.GeneratorMasinaSpalatRufe;


public class WindowMSR extends javax.swing.JFrame {

    /**
     * Creates new form WindowMSR
     */
    public WindowMSR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Masina de spalat rufe", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Producator", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox1.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bosch", "Beko", "Whirlpool", "Indesit", "Arctic", "Selecteaza o categorie" }));
        jComboBox1.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 60));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Pret", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox2.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intre 200 si 500 de lei", "Intre 500 si 1.000 de lei", "Intre 1.000 si 1.500 de lei", "Intre 1.500 si 2.000 de lei", "Intre 2.000 si 3.000 de lei", "Peste 3.000 de lei", "Selecteaza o categorie" }));
        jComboBox2.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Culoare", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox3.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alb", "Gri", "Argintiu", "Negru", "Albastru", "Rosu", "Portocaliu", "Selecteaza o categorie" }));
        jComboBox3.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Putere consumata", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox4.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 1.000 W", "Intre 1.000 si 1.500 W", "Intre 1.500 si 2.000 W", "Peste 2.000 W", "Selecteaza o categorie" }));
        jComboBox4.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox4, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        jPanel8.setBackground(new java.awt.Color(153, 255, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Rotatii", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox5.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 800 rot/min", "Intre 800 si 1.000 rot/min", "Intre 1.000 si 1.500 rot/min", "Peste 1.500 rot/min", "Selecteaza o categorie" }));
        jComboBox5.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, 0, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 313, 170, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("CAUTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Rezultate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(672, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MasinaSpalatRufe[] obiectMSR = new MasinaSpalatRufe[10];
        
        /*
        obiectMSR[0] = new MasinaSpalatRufe("Masina de spalat rufe", "Bosch", 230.0, "Negru", 470.0, 300.0, 350.0);
        obiectMSR[1] = new MasinaSpalatRufe("Masina de spalat rufe", "Beko", 2475.0, "Albastru", 6700.0, 3450.0, 935.0);
        obiectMSR[2] = new MasinaSpalatRufe("Masina de spalat rufe", "Whirlpool", 530.0, "Alb", 750.0, 500.0, 3750.0);
        obiectMSR[3] = new MasinaSpalatRufe("Masina de spalat rufe", "Indesit", 730.0, "Gri", 8900.0, 500.0, 3750.0);
        obiectMSR[4] = new MasinaSpalatRufe("Masina de spalat rufe", "Arctic", 1340.0, "Argintiu", 750.0, 500.0, 3750.0);
        obiectMSR[5] = new MasinaSpalatRufe("Masina de spalat rufe", "Whirlpool", 2630.0, "Rosu",250.0, 2400.0, 250.0);
        obiectMSR[6] = new MasinaSpalatRufe("Masina de spalat rufe", "Beko", 430.0, "Portocaliu", 790.0, 3500.0, 750.0);
        obiectMSR[7] = new MasinaSpalatRufe("Masina de spalat rufe", "Indesit", 2600.0, "Portocaliu", 3750.0, 5000.0, 3750.0);
        obiectMSR[8] = new MasinaSpalatRufe("Masina de spalat rufe", "Arcitc", 790.0, "Negru", 7000.0, 350.0, 375.0);
        obiectMSR[9] = new MasinaSpalatRufe("Masina de spalat rufe", "Beko", 1200.0, "Rosu", 700.0, 3500.0, 3750.0);
        */
        
        ArrayList<MasinaSpalatRufe> listaMasinaSpalatRufe = GeneratorMasinaSpalatRufe
				.genereazaRandomMasinaSpalatRufe(10);
		for (MasinaSpalatRufe unMasinaSpalatRufe : listaMasinaSpalatRufe)
			System.out.println(unMasinaSpalatRufe);
        
                
        obiectMSR[0]=listaMasinaSpalatRufe.get(0);
        obiectMSR[1]=listaMasinaSpalatRufe.get(1);
        obiectMSR[2]=listaMasinaSpalatRufe.get(2);
        obiectMSR[3]=listaMasinaSpalatRufe.get(3);
        obiectMSR[4]=listaMasinaSpalatRufe.get(4);
        obiectMSR[5]=listaMasinaSpalatRufe.get(5);
        obiectMSR[6]=listaMasinaSpalatRufe.get(6);
        obiectMSR[7]=listaMasinaSpalatRufe.get(7);
        obiectMSR[8]=listaMasinaSpalatRufe.get(8);
        obiectMSR[9]=listaMasinaSpalatRufe.get(9);
        
        
        textArea1.setText(null);
        boolean verificareText = true;
        for(int i = 0; i < obiectMSR.length; i++){
            
            boolean valid = true;
            if(jComboBox1.getSelectedItem() != "Selecteaza o categorie" && obiectMSR[i].getProducator() != jComboBox1.getSelectedItem()) valid = false;
            
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 0  && (obiectMSR[i].getPret() < 200 || obiectMSR[i].getPret() > 500)) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 1  && (obiectMSR[i].getPret() < 500 || obiectMSR[i].getPret() > 1000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 2  && (obiectMSR[i].getPret() < 1000 || obiectMSR[i].getPret() > 1500 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 3  && (obiectMSR[i].getPret() < 1500 || obiectMSR[i].getPret() > 2000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 4  && (obiectMSR[i].getPret() < 2000 || obiectMSR[i].getPret() > 3000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 5  && obiectMSR[i].getPret() < 3000 ) valid = false;
            
            if(jComboBox3.getSelectedItem() != "Selecteaza o categorie" && obiectMSR[i].getCuloare()!= jComboBox3.getSelectedItem()) valid = false;
            
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 0  && obiectMSR[i].getPutereConsumata()> 1000) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 1  && (obiectMSR[i].getPutereConsumata() < 1000 || obiectMSR[i].getPutereConsumata() > 1500 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 2  && (obiectMSR[i].getPutereConsumata() < 1500 || obiectMSR[i].getPutereConsumata() > 2000 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 3  && obiectMSR[i].getPutereConsumata() < 2000 ) valid = false;
            
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 0  && obiectMSR[i].getRotatii() > 800) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 1  && (obiectMSR[i].getRotatii() < 800 || obiectMSR[i].getRotatii() > 1000 )) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 2  && (obiectMSR[i].getRotatii() < 1000 || obiectMSR[i].getRotatii() > 1500 )) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 3  && obiectMSR[i].getRotatii() < 1500 ) valid = false;
            
            if(valid) {
                textArea1.append(obiectMSR[i].afisare());
                verificareText = false;
            }
        }
        if(verificareText) textArea1.append("Nu s-a gasit niciun rezultat!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowMSR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
