/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsVali;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import pachet.clase.valentin.Monitor;
import pachet.clasegeneratoare.vali.GeneratorMonitor;


public class WindowMN extends javax.swing.JFrame {

    /**
     * Creates new form WindowMN
     */
    public WindowMN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 255), new java.awt.Color(102, 0, 102)), "Monitor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(204, 0, 0)), "Producator", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "Dell", "Asus", "Acer", "Philips", "LG", "Selecteaza o categorie" }));
        jComboBox1.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 168, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(204, 0, 0)), "Pret", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intre 200 si 500 de lei", "Intre 500 si 1.000 de lei", "Intre 1.000 si 1.500 de lei", "Intre 1.500 si 2.000 de lei", "Peste 2.000", "Selecteaza o categorie" }));
        jComboBox2.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox2, 0, 168, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(204, 0, 0)), "Culoare", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alb", "Gri", "Negru", "Argintiu", "Auriu", "Selecteaza o categorie" }));
        jComboBox3.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox3, 0, 168, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(204, 0, 0)), "Putere consumata", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 60 W", "Intre 60 W si 80 W", "Peste 80 W", "Selecteaza o categorie" }));
        jComboBox4.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox4, 0, 168, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, -1));

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(204, 0, 0)), "Rata de refresh", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "60 Hz", "75 Hz", "120 Hz", "144 Hz", "240 Hz", "Selecteaza o categorie" }));
        jComboBox5.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox5, 0, 168, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("CAUTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jButton3.setText("Import");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jButton4.setText("Export");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(204, 0, 0)), "Rezultate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 420, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(672, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Monitor[] obiectMN=new Monitor[10];
        //String numeProdus,String producator,double pret,String culoare,double putereConsumata,double rataRefresh,double diagonala,String formatEcran,String rezolutieOptima,double timpRaspuns,String functiiSpeciale
        /*
        obiectMN[0]=new Monitor("Monitor","Lenovo",1300,"Negru",125,120,27,"ultraWide","1024x668",7,"webcam");
        obiectMN[1]=new Monitor("Monitor","Samsung",1250,"Alb",130,144,20,"Wide","1024x668",4,"touchscreen");
        obiectMN[2]=new Monitor("Monitor","Dell",1100,"Negru",125,120,20,"ultraWide","1024x668",7,"webcam");
        obiectMN[3]=new Monitor("Monitor","Asus",1400,"Alb",120,60,27,"ultraWide","1024x668",7,"webcam");
        obiectMN[4]=new Monitor("Monitor","Lenovo",900,"Gri",90,75,27,"ultraWide","1024x668",7,"webcam");
        obiectMN[5]=new Monitor("Monitor","HP",800,"Negru",80,100,27,"ultraWide","1024x668",7,"touchscreen");
        obiectMN[6]=new Monitor("Monitor","MSI",1159.99,"Alb",90,120,27,"ultraWide","1024x668",7,"webcam");
        obiectMN[7]=new Monitor("Monitor","Lenovo",1400,"Negru",100,144,27,"ultraWide","1024x668",7,"webcam");
        obiectMN[8]=new Monitor("Monitor","Samsung",700,"Argintiu",120,240,27,"ultraWide","1024x668",7,"webcam");
        obiectMN[9]=new Monitor("Monitor","Dell",1500,"Auriu",190,240,27,"Wide","1024x668",7,"touchscreen");
        */
        
        ArrayList<Monitor> listaMonitor = GeneratorMonitor.genereazaRandomMonitor(10);
		for (Monitor unMonitor : listaMonitor)
			System.out.println(unMonitor);
                
                
        obiectMN[0]=listaMonitor.get(0);
        obiectMN[1]=listaMonitor.get(1);
        obiectMN[2]=listaMonitor.get(2);
        obiectMN[3]=listaMonitor.get(3);
        obiectMN[4]=listaMonitor.get(4);
        obiectMN[5]=listaMonitor.get(5);
        obiectMN[6]=listaMonitor.get(6);
        obiectMN[7]=listaMonitor.get(7);
        obiectMN[8]=listaMonitor.get(8);
        obiectMN[9]=listaMonitor.get(9);
        
        textArea1.setText(null);
        boolean verificareText = true;
        for(int i = 0; i < obiectMN.length; i++){
            
            boolean valid = true;
            if(jComboBox1.getSelectedItem() != "Selecteaza o categorie" && obiectMN[i].getProducator() != jComboBox1.getSelectedItem()) valid = false;
            
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 0  && (obiectMN[i].getPret() < 200 || obiectMN[i].getPret() > 500)) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 1  && (obiectMN[i].getPret() < 500 || obiectMN[i].getPret() > 1000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 2  && (obiectMN[i].getPret() < 1000 || obiectMN[i].getPret() > 1500 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 3  && (obiectMN[i].getPret() < 1500 || obiectMN[i].getPret() > 2000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 4  && obiectMN[i].getPret() < 2000) valid = false;
            
            if(jComboBox3.getSelectedItem() != "Selecteaza o categorie" && obiectMN[i].getCuloare()!= jComboBox3.getSelectedItem()) valid = false;
            
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 0  && obiectMN[i].getPutereConsumata()> 60) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 1  && (obiectMN[i].getPutereConsumata() < 60 || obiectMN[i].getPutereConsumata() > 80 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 2  && obiectMN[i].getPutereConsumata() < 80 ) valid = false;
            
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 0  && obiectMN[i].getRataRefresh() != 60) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 1  && obiectMN[i].getRataRefresh() != 75) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 2  && obiectMN[i].getRataRefresh() != 100) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 3  && obiectMN[i].getRataRefresh() != 120) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 4  && obiectMN[i].getRataRefresh() != 144) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 5  && obiectMN[i].getRataRefresh() != 240) valid = false;
            /*
            if(valid) {
                textArea1.append(obiectMN[i].afisare());
                verificareText = false;
            }
            */
            
            if(valid) {
                 //textArea1.append(obiectMN[i].afisare());
                // verificareText = false;
                

Date date = new Date();
SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy_HH-mm-ss");
String fileName = "obiectMN_" + formatter.format(date) + ".txt";
File file = new File(fileName);
FileWriter writer = null;
                


                try {
                    writer = new FileWriter(file,true);
                } catch (IOException ex) {
                    Logger.getLogger(WindowMN.class.getName()).log(Level.SEVERE, null, ex);
                }


                try {
                   
                    writer.write(obiectMN[i].afisare());
                } catch (IOException ex) {
                    Logger.getLogger(WindowMN.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(WindowMN.class.getName()).log(Level.SEVERE, null, ex);
                }

                  
                textArea1.append(obiectMN[i].afisare());
                 verificareText = false;
            }
            
            
            
            
            
            
        }
        if(verificareText) textArea1.append("Nu s-a gasit niciun rezultat!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = chooser.getSelectedFile();
                FileReader reader = new FileReader(file);
                BufferedReader bufferedReader = new BufferedReader(reader);

                textArea1.setText(null);
                String line;
                while((line = bufferedReader.readLine()) != null) {
                    textArea1.append(line + System.lineSeparator());
                }
                bufferedReader.close();
            } catch(IOException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = chooser.getSelectedFile();
                FileWriter writer = new FileWriter(file);
                writer.write(textArea1.getText());
                writer.close();
            } catch(IOException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowMN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
