/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowsVali;

import java.util.ArrayList;
import pachet.clase.valentin.MasinaSpalatVase;
import pachet.clasegeneratoare.vali.GeneratorMasinaSpalatVase;

/**
 *
 * @author sorin
 */
public class WindowMSV extends javax.swing.JFrame {

    /**
     * Creates new form WindowMSV
     */
    public WindowMSV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Masina de spalat vase", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Producator", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox1.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bosch", "Beko", "Whirlpool", "Indesit", "Arctic", "Selecteaza o categorie" }));
        jComboBox1.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Pret", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox2.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intre 500 si 1.000 de lei", "Intre 1.000 si 1.500 de lei", "Intre 1.500 si 2.000 de lei", "Intre 2.000 si 3.000 de lei", "Peste 3.000 de lei", "Selecteaza o categorie" }));
        jComboBox2.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Culoare", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox3.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alb", "Argintiu", "Negru", "Selecteaza o categorie" }));
        jComboBox3.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Putere consumata", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox4.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 1.000 W", "Intre 1.000 si 1.500 W", "Intre 1.500 si 2.000 W", "Peste 2.000 W", "Selecteaza o categorie" }));
        jComboBox4.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox4, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        jPanel7.setBackground(new java.awt.Color(153, 255, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Numar seturi", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jComboBox5.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 5", "Intre 5 si 9", "Intre 10 si 15", "Intre 16 si 20", "Selecteaza o categorie" }));
        jComboBox5.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("CAUTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(51, 51, 51)), "Rezultate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(672, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        MasinaSpalatVase[] obiectMSV = new MasinaSpalatVase[10];
        /*
        obiectMSV[0] = new MasinaSpalatVase("Masina de spalat vase", "Samsung", 230.0, "Negru", 470.0, 300, 350.0);
        obiectMSV[1] = new MasinaSpalatVase("Masina de spalat vase", "LG", 2475.0, "Argintiu", 6700.0, 3450, 935.0);
        obiectMSV[2] = new MasinaSpalatVase("Masina de spalat vase", "Panasonic", 530.0, "Alb", 750.0, 500, 3750.0);
        obiectMSV[3] = new MasinaSpalatVase("Masina de spalat vase", "Sony", 730.0, "Argintiu", 8900.0, 500, 3750.0);
        obiectMSV[4] = new MasinaSpalatVase("Masina de spalat vase", "Toshiba", 1340.0, "Argintiu", 750.0, 500, 3750.0);
        obiectMSV[5] = new MasinaSpalatVase("Masina de spalat vase", "Samsung", 2630.0, "Negru",250.0, 2400, 250.0);
        obiectMSV[6] = new MasinaSpalatVase("Masina de spalat vase", "LG", 430.0, "Alb", 790.0, 3500, 750.0);
        obiectMSV[7] = new MasinaSpalatVase("Masina de spalat vase", "Panasonic", 2600.0, "Argintiu", 3750.0, 5000, 3750.0);
        obiectMSV[8] = new MasinaSpalatVase("Masina de spalat vase", "Sony", 790.0, "Negru", 7000.0, 350, 375.0);
        obiectMSV[9] = new MasinaSpalatVase("Masina de spalat vase", "Toshiba", 1200.0, "Alb", 700.0, 3500, 3750.0);
        */
        
        ArrayList<MasinaSpalatVase> listaMasinaSpalatVase = GeneratorMasinaSpalatVase
				.genereazaRandomMasinaSpalatVase(10);
		for (MasinaSpalatVase unMasinaSpalatVase : listaMasinaSpalatVase)
			System.out.println(unMasinaSpalatVase);
        
                
        obiectMSV[0]=listaMasinaSpalatVase.get(0);
        obiectMSV[1]=listaMasinaSpalatVase.get(1);
        obiectMSV[2]=listaMasinaSpalatVase.get(2);
        obiectMSV[3]=listaMasinaSpalatVase.get(3);
        obiectMSV[4]=listaMasinaSpalatVase.get(4);
        obiectMSV[5]=listaMasinaSpalatVase.get(5);
        obiectMSV[6]=listaMasinaSpalatVase.get(6);
        obiectMSV[7]=listaMasinaSpalatVase.get(7);
        obiectMSV[8]=listaMasinaSpalatVase.get(8);
        obiectMSV[9]=listaMasinaSpalatVase.get(9);
                
                
                
        textArea1.setText(null);
        boolean verificareText = true;
        for(int i = 0; i < obiectMSV.length; i++){
            
            boolean valid = true;
            if(jComboBox1.getSelectedItem() != "Selecteaza o categorie" && obiectMSV[i].getProducator() != jComboBox1.getSelectedItem()) valid = false;
            
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 0  && (obiectMSV[i].getPret() < 500 || obiectMSV[i].getPret() > 1000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 1  && (obiectMSV[i].getPret() < 1000 || obiectMSV[i].getPret() > 1500 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 2  && (obiectMSV[i].getPret() < 1500 || obiectMSV[i].getPret() > 2000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 3  && (obiectMSV[i].getPret() < 2000 || obiectMSV[i].getPret() > 3000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 4  && obiectMSV[i].getPret() < 3000 ) valid = false;
            
            if(jComboBox3.getSelectedItem() != "Selecteaza o categorie" && obiectMSV[i].getCuloare()!= jComboBox3.getSelectedItem()) valid = false;
            
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 0  && obiectMSV[i].getPutereConsumata()> 1000) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 1  && (obiectMSV[i].getPutereConsumata() < 1000 || obiectMSV[i].getPutereConsumata() > 1500 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 2  && (obiectMSV[i].getPutereConsumata() < 1500 || obiectMSV[i].getPutereConsumata() > 2000 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 3  && obiectMSV[i].getPutereConsumata() < 2000 ) valid = false;
            
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 0  && obiectMSV[i].getNumarSeturi() > 5) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 1  && (obiectMSV[i].getNumarSeturi() < 5 || obiectMSV[i].getNumarSeturi() > 9 )) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 2  && (obiectMSV[i].getNumarSeturi() < 10 || obiectMSV[i].getNumarSeturi() > 15 )) valid = false;
            if(jComboBox5.getSelectedItem() != "Selecteaza o categorie"&& jComboBox5.getSelectedIndex() == 3  && (obiectMSV[i].getNumarSeturi() < 16 || obiectMSV[i].getNumarSeturi() > 20 )) valid = false;
            
            if(valid) {
                textArea1.append(obiectMSV[i].afisare());
                verificareText = false;
            }
        }
        if(verificareText) textArea1.append("Nu s-a gasit niciun rezultat!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowMSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
