/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windowsVali;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;
import pachet.teste.valentin.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import pachet.clase.valentin.FierCalcat;
import pachet.clasegeneratoare.vali.GeneratorAerConditionat;
import pachet.clasegeneratoare.vali.GeneratorFierCalcat;
import pachet.clasegeneratoare.vali.GeneratorMasinaSpalatRufe;
import pachet.clasegeneratoare.vali.GeneratorMasinaSpalatVase;
import pachet.clasegeneratoare.vali.GeneratorMonitor;
import pachet.clase.valentin.*;
import pachet.clasefilter.vali.*;
import pachet.clasegeneratoare.vali.*;

/**
 *
 * @author Valentin
 */
public class WindowAC extends javax.swing.JFrame {

    /**
     * Creates new form WindowsAC
     */
    public WindowAC() {
        initComponents();
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(153, 153, 255)), "Aer conditionat", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(153, 153, 255)), "Producator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jComboBox1.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MDV", "Vivax", "Daikin", "Hitachi", "Gree", "LG", "Selecteaza o categorie" }));
        jComboBox1.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 178, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, 190, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(153, 153, 255)), "Pret", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jComboBox2.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 100 de lei", "Intre 100 si 200 de lei", "Intre 200 si 500 de lei", "Intre 500 si 1.000 de lei", "Intre 1.000 si 1.500 de lei", "Intre 1.500 si 2.000 de lei", "Peste 2.000\t", "Selecteaza o categorie" }));
        jComboBox2.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 178, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 100, 190, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(153, 153, 255)), "Culoare", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jComboBox3.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alb", "verde", "negru", "albastru", "rosu", "galben", "Selecteaza o categorie" }));
        jComboBox3.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox3, 0, 178, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 171, 190, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(153, 153, 255)), "Putere consumata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jComboBox4.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub 500 W", "Intre 500 si 1.000 W", "Intre 1.000 si 1.500 W", "Peste 1.500 W", "Selecteaza o categorie" }));
        jComboBox4.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox4, 0, 178, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, 190, -1));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(153, 153, 255)), "Arie acoperita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jComboBox6.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5-10", "11-15", ">15", "Selecteaza o categorie" }));
        jComboBox6.setSelectedItem("Selecteaza o categorie");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox6, 0, 178, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 313, 190, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("CAUTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jButton2.setText("Import");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jButton3.setText("Export");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 462));

        jPanel8.setBackground(new java.awt.Color(102, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(204, 204, 255)), "Rezultate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea1.setBackground(new java.awt.Color(255, 255, 204));
        textArea1.setEditable(false);
        jPanel8.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 430));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 6, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //private boolean flag = false; // Initialize flag variable
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            
         //Check value of flag
         //if (!flag) {
             //Set flag to true
            // flag = true;


// TODO add your handling code here:
        AerConditionat[] obiectAC=new AerConditionat[10];
       /*
        obiectAC[0]=new AerConditionat("Aer Conditionat","Beko",500,"Alb",50,"A",10,5);
        obiectAC[1]=new AerConditionat("Aer Conditionat","Bosch",750,"Gri",70,"A+",15,3);
        obiectAC[2]=new AerConditionat("Aer Conditionat","Myria",550,"Negru",25,"B",20,5);
        obiectAC[3]=new AerConditionat("Aer Conditionat","Domo",400,"Rosu",100,"B+",5,3);
        obiectAC[4]=new AerConditionat("Aer Conditionat","Heinner",600,"Alb",50,"A",10,5);
        obiectAC[5]=new AerConditionat("Aer Conditionat","Philips",650,"Negru",85,"A+",15,3);
        obiectAC[6]=new AerConditionat("Aer Conditionat","Victronic",750,"Gri",75,"B",10,5);
        obiectAC[7]=new AerConditionat("Aer Conditionat","Beko",500,"Alb",55,"C",5,3);
        obiectAC[8]=new AerConditionat("Aer Conditionat","Bosch",800,"Ros",65,"B+",15,5);
        obiectAC[9]=new AerConditionat("Aer Conditionat","Myria",850,"Alb",90,"A+",10,3);
        */

        ArrayList<AerConditionat> listaAerConditionat = GeneratorAerConditionat.genereazaRandomAerConditionat(10);
		for (AerConditionat unAerConditionat : listaAerConditionat)
                System.out.println(unAerConditionat);
                
                
        obiectAC[0]=listaAerConditionat.get(0);
        obiectAC[1]=listaAerConditionat.get(1);
        obiectAC[2]=listaAerConditionat.get(2);
        obiectAC[3]=listaAerConditionat.get(3);
        obiectAC[4]=listaAerConditionat.get(4);
        obiectAC[5]=listaAerConditionat.get(5);
        obiectAC[6]=listaAerConditionat.get(6);
        obiectAC[7]=listaAerConditionat.get(7);
        obiectAC[8]=listaAerConditionat.get(8);
        obiectAC[9]=listaAerConditionat.get(9);
               
                
                
        
        
        textArea1.setText(null);
        boolean verificareText = true;
        for(int i = 0; i < obiectAC.length; i++){

            boolean valid = true;
            if(jComboBox1.getSelectedItem() != "Selecteaza o categorie" && obiectAC[i].getProducator() != jComboBox1.getSelectedItem()) valid = false;

            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 0  && (obiectAC[i].getPret() > 100 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 1  && (obiectAC[i].getPret() < 100 || obiectAC[i].getPret() > 200)) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 2  && (obiectAC[i].getPret() < 200 || obiectAC[i].getPret() > 500)) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 3  && (obiectAC[i].getPret() < 500 || obiectAC[i].getPret() > 1000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 4  && (obiectAC[i].getPret() < 1000 || obiectAC[i].getPret() > 1500 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 5  && (obiectAC[i].getPret() < 1500 || obiectAC[i].getPret() > 2000 )) valid = false;
            if(jComboBox2.getSelectedItem() != "Selecteaza o categorie" && jComboBox2.getSelectedIndex() == 6  && (obiectAC[i].getPret() < 2000 )) valid = false;

            if(jComboBox3.getSelectedItem() != "Selecteaza o categorie" && obiectAC[i].getCuloare()!= jComboBox3.getSelectedItem()) valid = false;

            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 0  && obiectAC[i].getPutereConsumata() > 500) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 1  && (obiectAC[i].getPutereConsumata() < 500 || obiectAC[i].getPutereConsumata() > 1000 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 2  && (obiectAC[i].getPutereConsumata() < 1000 || obiectAC[i].getPutereConsumata() > 1500 )) valid = false;
            if(jComboBox4.getSelectedItem() != "Selecteaza o categorie"&& jComboBox4.getSelectedIndex() == 3  && obiectAC[i].getPutereConsumata() < 1500 ) valid = false;

            if(jComboBox6.getSelectedItem() != "Selecteaza o categorie"&& jComboBox6.getSelectedIndex() == 0  && (obiectAC[i].getarieAcoperita() < 5 || obiectAC[i].getarieAcoperita() > 10 )) valid = false;
            if(jComboBox6.getSelectedItem() != "Selecteaza o categorie"&& jComboBox6.getSelectedIndex() == 1  && (obiectAC[i].getarieAcoperita() < 11 || obiectAC[i].getarieAcoperita() > 15)) valid = false;
            if(jComboBox6.getSelectedItem() != "Selecteaza o categorie"&& jComboBox6.getSelectedIndex() == 2  && obiectAC[i].getarieAcoperita() < 15 ) valid = false;

            /*
            if(valid) {
                textArea1.append(obiectAC[i].afisare());
                verificareText = false;
            }
            */
            
             if(valid) {
                 //textArea1.append(obiectAC[i].afisare());
                // verificareText = false;
                

Date date = new Date();
SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy_HH-mm-ss");
String fileName = "obiectAC_" + formatter.format(date) + ".txt";
File file = new File(fileName);
FileWriter writer = null;
                


                try {
                    writer = new FileWriter(file,true);
                } catch (IOException ex) {
                    Logger.getLogger(WindowAC.class.getName()).log(Level.SEVERE, null, ex);
                }


                try {
                   
                    writer.write(obiectAC[i].afisare());
                } catch (IOException ex) {
                    Logger.getLogger(WindowAC.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(WindowAC.class.getName()).log(Level.SEVERE, null, ex);
                }

                  
                textArea1.append(obiectAC[i].afisare());
                 verificareText = false;
            }
             
         
            
        }
        if(verificareText) textArea1.append("Nu s-a gasit niciun rezultat!");

      
   
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    int returnVal = chooser.showOpenDialog(null);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
        try {
            File file = chooser.getSelectedFile();
            FileReader reader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(reader);
            
            textArea1.setText(null);
            String line;
            while((line = bufferedReader.readLine()) != null) {
                textArea1.append(line + System.lineSeparator());
            }
            bufferedReader.close();
        } catch(IOException e) {
            e.printStackTrace();
        }
    }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    int returnVal = chooser.showSaveDialog(null);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
        try {
            File file = chooser.getSelectedFile();
            FileWriter writer = new FileWriter(file);
            writer.write(textArea1.getText());
            writer.close();
        } catch(IOException e) {
            e.printStackTrace();
        }
    }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
